version: '3.5'

services:

  tickets-service:
    build:
      context: ./ticket
      dockerfile: Dockerfile
    container_name: tickets-service
    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tickets-db:5432/tickets
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

    depends_on:
      - tickets-db

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

    depends_on:
      - auth-db

  tickets-db:
    image: postgres:14.3-alpine
    container_name: tickets-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tickets
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  auth-db:
    image: postgres:14.3-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"

networks:
  default:
